language: java
jdk:
  - openjdk8

branches:
  only:
    - beststar

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
#  gradle 버전 변경
  - sudo wget https://services.gradle.org/distributions/gradle-6.8-bin.zip
  - sudo unzip -qq gradle-6.8-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.8
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -version
  - gradle wrap
  - chmod +x gradlew

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: freelec-springboot-build-beststar # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hwksdream23@gmail.com